name: branch

on: [pull_request]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: PR files changed detector
    steps:
      - name: Annotate PR
        uses: hasaan21/files-changed-detector-action@v1.1-alpha.1.3
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
